default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wechat_geraldhms_development

test:
  <<: *default
  database: wechat_geraldhms_test

production:
  <<: *default
  database: wechat_geraldhms_production
